apiVersion: v1
kind: Pod
metadata:
  name: newpetclinictest1
  
spec:
  containers:
  - name: newpetclinictest1
    image: coeazurecontainersreg.azurecr.io/jagadt/newpetclinic:180
    ports:
    - containerPort: 8080
      protocol: TCP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: newpetclinictest1deployment
  
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        name: service-b
        app: demo
    spec:
      containers:
      - name: newpetclinictest1
        image: coeazurecontainersreg.azurecr.io/jagadt/newpetclinic:180
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: newpetclinictest1
  
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: newpetclinictest1
    app: petclinic
  type: NodePort
